name: english_mvvm_provider_clean
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  animate_do: ^4.2.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  circular_countdown_timer: ^0.2.4
  dart_openai: ^6.1.1
  firebase_auth: ^6.1.0
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  form_validator: ^2.1.1
  go_router: ^16.2.2
  google_sign_in: ^6.3.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  sizer: ^3.1.3
  supabase_flutter: ^2.10.3

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/files/words.json
    - assets/images/logo.png
    - assets/images/logo_google.png
    - .env

  fonts:
    - family: Comic Relief
      fonts:
        - asset: assets/fonts/ComicRelief-Regular.ttf
        - asset: assets/fonts/ComicRelief-Bold.ttf
          weight: 700
